#!/bin/bash

if [[ $(uname -s) == *NT* ]]; then
    echo "Building for Windows"
elif [[ $(uname -s) == *Darwin* ]]; then
    echo "Building for Mac"
else
    echo "Building for Linux"
fi

cargo bundle --format msi --release
