#!/bin/bash

if [[ $(uname -s) == *NT* ]]; then
    echo "Building for Windows"
		format="msi"
elif [[ $(uname -s) == *Darwin* ]]; then
    echo "Building for Mac"
		format="osx"
else
    echo "Building for Linux"
		format="deb"
fi

cargo bundle --format ${format} --release
