[package]
name = "stash"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", default-features = false, features = [
    "default_fonts",
    "glow",
] }
egui = { version = "0.27.2", features = [
    # "persistence",
    "log",
    "rayon",
    "unity",
] }
image = "0.25.1"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = { version = "1.0.117" }
tray-icon = { version = "0.14.0" }
tokio = { version = "1.33.0", features = [
    "sync",
    "rt",
    "rt-multi-thread",
    "time",
] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
